Story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls')),
]

schedule/urls.py
from django.urls import path
from . import views

app_name = "schedule"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='about'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/<int:pk>', views.delete_schedule, name='delete_schedule'),
    path('skills/', views.skills, name='skills'),
    path('exp/', views.exp, name='exp'),
    path('contact/', views.contact, name='contact'),
    path('about/swot/', views.swot, name='swot'),
]

schedule/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model):
    activity = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    datetime = models.DateTimeField()

    def __str__(self):
        return self.activity

schedule/views.py
from django.shortcuts import render
from .models import Schedule
from django.shortcuts import redirect

# Create your views here.
def homepage(request):
    return render(request, 'Homepage.html')

def about(request):
    return render(request, 'About.html')

def schedule(request):
    list_of_schedule = Schedule.objects.all().order_by('datetime')
    if request.method == 'POST':
        activity_r = request.POST.get('activity')
        place_r = request.POST.get('place')
        category_r = request.POST.get('category')
        datetime_r = request.POST.get('datetime')

        schedule = Schedule(activity=activity_r, place=place_r, category=category_r, datetime=datetime_r)
        schedule.save()
        return render(request, 'Schedule.html', {'schedules' : list_of_schedule})
    else:
        return render(request, 'Schedule.html', {'schedules' : list_of_schedule})

def delete_schedule(request, pk):
    list_of_schedule = Schedule.objects.all()
    obj = list_of_schedule.get(id=pk)
    obj.delete()
    return redirect('/schedule/')

def skills(request):
    return render(request, 'Skills.html')

def exp(request):
    return render(request, 'Experiences.html')

def contact(request):
    return render(request, 'Contact.html')

def swot(request):
    return render(request, 'Swot.html')

schedule/templates/About.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | About Me</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/about_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>  
        

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">About</div>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Schedule_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:schedule' %}"><div class="text">Schedule</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:exp' %}"><div class="text">Exp</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:contact' %}"><div class="text">Contact</div></a>
                    </div>
                </div>
                
            </div>
        </div>

        <div class="container-fluid left-right-most">
            <div class="header top right">
                <!-- fill the header with dropdown -->
                <div class="dropdown ">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                      Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'schedule:homepage' %}">Home</a>
                        <a class="dropdown-item disabled" href="#">About Me</a>
                        <a class="dropdown-item" href="{% url 'schedule:schedule' %}">Schedule</a>
                        <a class="dropdown-item" href="{% url 'schedule:skills' %}">Skills</a>
                        <a class="dropdown-item" href="{% url 'schedule:exp' %}">Exp</a>
                        <a class="dropdown-item" href="{% url 'schedule:contact' %}">Contact</a>
                    </div>
                </div>
            </div>
            
            <div id="about">
                <div class="d-flex flex-column margin-left">
                    <h1 class="title">About Me</h1>
                    <div class="row">
                        <div class="col-md-4 left-right-most center">
                            <picture>
                                <source class="landscape_photo" media="(max-width: 767px)" srcset="{% static 'images/Photo-landscape-crop.jpg' %}" />
                                <img class=".mx-auto .d-block profile" src="{% static 'images/Photo.jpg' %}" alt="main photo" />
                            </picture>
                        </div>
                        <div class="col-md-7 left-right-most">
                            <p class="leftmost">
                                I’m a highly <strong>motivated</strong> and <strong>hardworking</strong> person. Excellent in <strong>team working</strong>  
                                and always try to be a <strong>professional</strong> at any possible time. I give someone chances to criticize my performance 
                                for the better. <br><br>
                                From a high school, my passion is <strong>technology</strong>. That's why I started learning in 
                                a computer science major. I really hope someday I could make something <strong>helpful</strong> with my knowledge 
                                and spread education about how technology can change our world.
                            </p>
                            <a href="{% url 'schedule:swot' %}" target="_blank"><img class="swot_icon" src="{% static 'images/Icon/SWOT_icon.png' %}" alt="swot icon" /></a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

schedule/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Contact</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/contact_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:about' %}"><div class="text">About</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Schedule_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:schedule' %}"><div class="text">Schedule</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:exp' %}"><div class="text">Exp</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">Contact</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid left-right-most">
            <div class="header right">
                <!-- fill the header with dropdown -->
                <div class="dropdown">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                        Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'schedule:homepage' %}">Home</a>
                        <a class="dropdown-item" href="{% url 'schedule:about' %}">About Me</a>
                        <a class="dropdown-item" href="{% url 'schedule:schedule' %}">schedule</a>
                        <a class="dropdown-item" href="{% url 'schedule:skills' %}">Skills</a>
                        <a class="dropdown-item" href="{% url 'schedule:exp' %}">Exp</a>
                        <a class="dropdown-item disabled" href="#">Contact</a>
                    </div>
                </div>
            </div>

            <div id="contact">
                <div class="d-flex flex-column margin-left center-icon">
                    <h1 class="title">Contact</h1>
                    <p>If you have any questions, don’t hesitate to ask me on</p>
                    <div class=".d-flex flex-row center-icon">
                        <a class="btn btn-link" href="mailto:jilham.luthfi15@gmail.com" target="_blank" role="button">
                            <img src="{% static 'images/Icon/Email.png' %}" alt="email icon" class="iconContact"/>
                        </a>
                        <a class="btn btn-link" href="https://www.linkedin.com/in/jilham-luthfi-78713417b/" target="_blank" role="button">
                            <img src="{% static 'images/Icon/LinkedIn.png' %}" alt="email icon" class="iconContact"/>
                        </a>
                        <a class="btn btn-link" href="https://www.instagram.com/mjilham_luthfi/" target="_blank" role="button">
                            <img src="{% static 'images/Icon/Instagram.png' %}" alt="email icon" class="iconContact" />
                        </a>
                        <a class="btn btn-link" href="https://twitter.com/Mjilham_luthfi" target="_blank" role="button">
                            <img src="{% static 'images/Icon/Twitter.png' %}" alt="email icon" class="iconContact" />
                        </a>
    
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

schedule/templates/Experiences.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Experiences</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/experiences_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="background_menu">
            <div class="d-flex flex-column justify-content-center menu-area">
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:homepage' %}"><div class="text">Home</div></a>
                    </div> 
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:about' %}"><div class="text">About</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Schedule_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:schedule' %}"><div class="text">Schedule</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:skills' %}"><div class="text">Skills</div></a>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <div class="text">Exp</div>
                    </div>
                </div>
                <div class="container center-icon">
                    <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                    <div class="overlay overlayFade">
                        <a href="{% url 'schedule:contact' %}"><div class="text">Contact</div></a>
                    </div>
                </div>
            </div>
        </div>


        <div class="container-fluid left-right-most">
            <div class="header right">
                <!-- fill the header with dropdown -->
                <div class="dropdown">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                        Menu
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'schedule:homepage' %}">Home</a>
                        <a class="dropdown-item" href="{% url 'schedule:about' %}">About Me</a>
                        <a class="dropdown-item" href="{% url 'schedule:schedule' %}">schedule</a>
                        <a class="dropdown-item" href="{% url 'schedule:skills' %}">Skills</a>
                        <a class="dropdown-item disabled" href="#">Exp</a>
                        <a class="dropdown-item" href="{% url 'schedule:contact' %}">Contact</a>
                    </div>
                </div>
            </div>

            <div id="exp" class="left-right-most">
                <div class="d-flex flex-column margin-left">
                    <h1 class="title">Experiences</h1>
                    <div class="d-flex flex-row small-size">
                        <div class="center-icon">
                            <img src="{% static 'images/Icon/PythonLogo.png' %}" alt="python logo" />
                            <h2>DDP0</h2>
                            <p>Mentor<br>July, 2019 - Aug, 2019</p>
                        </div>
                        <div class="center-icon">
                            <img src="{% static 'images/Icon/CGTLogo.png' %}" alt="CGT logo" />
                            <h2>Computers Get Together</h2>
                            <p>Staff of Decoration<br>Feb, 2019 - April, 2019</p>
                        </div>
                        <div class="center-icon">
                            <img src="{% static 'images/Icon/BEM Fasilkom UI Logo.png' %}" alt="BEM Fasilkom UI logo" />
                            <h2>BEM Fasilkom UI</h2>
                            <p>Staff of Student Advocacy and Welfare<br>Feb, 2019 - present</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

schedule/templates/Homepage.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Jilham Luthfi | Portfolio Website</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/homepage_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="homepage" class="d-flex flex-column justify-content-center">
            <h1 class="titleHomepage">HI</h1>
            <p>I'm <strong>Jilham Luthfi</strong><br>and I'm an undergraduate student of Computer Science</p>
            <a class="btn btn-outline-dark btn-lg" href="{% url 'schedule:about' %}">find more</a>
        </div>
    </body>
</html>

schedule/templates/Schedule.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Jilham Luthfi | Schedule</title>
        <meta charset="utf-8">

        <!-- Connect to external CSS file -->
        <link rel="stylesheet" href="{% static 'css/menu_bar_style.css' %}">
        <link rel="stylesheet" href="{% static 'css/schedule_style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <!-- Connect the fonts from google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">

        <!-- Set the size which can be fit to any screen devices-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="menu_bar">
            <div class="background_menu">
                <div class="d-flex flex-column justify-content-center menu-area">
                    <div class="container center-icon">
                        <img src="{% static 'images/Icon/Home_icon.png' %}" alt="img" class="image" />
                        <div class="overlay overlayFade">
                            <a href="{% url 'schedule:homepage' %}"><div class="text">Home</div></a>
                        </div> 
                    </div>
                    <div class="container center-icon">
                        <img src="{% static 'images/Icon/About_icon.png' %}" alt="img" class="image" />
                        <div class="overlay overlayFade">
                            <a href="{% url 'schedule:about' %}"><div class="text">About</div></a>
                        </div>
                    </div>
                    <div class="container center-icon">
                        <img src="{% static 'images/Icon/Schedule_icon.png' %}" alt="img" class="image" />
                        <div class="overlay overlayFade">
                            <div class="text">Schedule</div>
                        </div>
                    </div>
                    <div class="container center-icon">
                        <img src="{% static 'images/Icon/Skills_icon.png' %}" alt="img" class="image" />
                        <div class="overlay overlayFade">
                            <a href="{% url 'schedule:skills' %}"><div class="text">Skills</div></a>
                        </div>
                    </div>
                    <div class="container center-icon">
                        <img src="{% static 'images/Icon/Experiences_icon.png' %}" alt="img" class="image" />
                        <div class="overlay overlayFade">
                            <a href="{% url 'schedule:exp' %}"><div class="text">Exp</div></a>
                        </div>
                    </div>
                    <div class="container center-icon">
                        <img src="{% static 'images/Icon/Contact_icon.png' %}" alt="img" class="image" />
                        <div class="overlay overlayFade">
                            <a href="{% url 'schedule:contact' %}"><div class="text">Contact</div></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        <div class="header top right">
            <!-- fill the header with dropdown -->
            <div class="dropdown">
                <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
                    Menu
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'schedule:homepage' %}">Home</a>
                    <a class="dropdown-item" href="{% url 'schedule:about' %}">About Me</a>
                    <a class="dropdown-item disabled" href="#">Schedule</a>
                    <a class="dropdown-item" href="{% url 'schedule:skills' %}">Skills</a>
                    <a class="dropdown-item" href="{% url 'schedule:exp' %}">Exp</a>
                    <a class="dropdown-item" href="{% url 'schedule:contact' %}">Contact</a>
                </div>
            </div>
        </div>

        <div id="schedule">
            <div class="d-flex flex-column margin-left">
                <h1 class="title">Schedule</h1>
                <form class="form_style" method="POST">
                    {% csrf_token %}
                    <div>
                        <h2>Maka a Schedule</h2>
                        <div class="form-group row justify-content-center">
                            <label for="activity" class="col-sm-2 col-form-label">Activity</label>
                            <div class="col-sm-4">
                                <input name="activity" type="text" class="form-control" id="activity" placeholder="what activity?">
                            </div>
                        </div>
                        <div class="form-group row justify-content-center">
                            <label for="place" class="col-sm-2 col-form-label">Place</label>
                            <div class="col-sm-4">
                                <input name="place" type="text" class="form-control" id="place" placeholder="where?">
                            </div>
                        </div>
                        <div class="form-group row justify-content-center">
                            <label for="category" class="col-sm-2 col-form-label">Category</label>
                            <div class="col-sm-4">
                                <input name="category" type="text" class="form-control" id="category" placeholder="what category?">
                        </div>
                        </div>
                        Date & Time:<br>
                        <input type="datetime-local" name="datetime"><br>
                        <input class="marginTop" type="submit" value="Save"> 
                    </div>
                </form>

                <div class="table-responsive my-5 px-4 py-2">
                    <table class="table table-active table-striped table_custom">
                        <thead>
                            <tr>
                            <th scope="col" class="no_size">No</th>
                            <th scope="col" class="dt_size">Time</th>
                            <th scope="col" class="a_size">Activity</th>
                            <th scope="col">-</th>
                            </tr>
                        </thead>
                        <tbody >
                            {% for schedule in schedules %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{schedule.datetime}}</td>
                                <td><strong>activity</strong>: {{schedule.activity}}<br>
                                    <strong>place</strong>: {{schedule.place}}<br>
                                    <strong>category</strong>: {{schedule.category}}
                                </td>
                                <td>
                                    <form action="{% url 'schedule:delete_schedule' schedule.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                                    </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

                
    </body>
</html>